config/routes.rb
HumboldtFantasy::Application.routes.draw do

  resources :line_posts
  resources :standings

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  
  get "static/example"

  get "static/all_picks"

  get "static/rules"

  get "static/pick_order"

  get "static/pick_history"

  root :to => "sessions#new"
  
  resources :users do
    resources :picks
  end

  resources :sessions

  resources :posts do
    resources :comments
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password, :password_confirmation
  
  has_many :picks
  has_many :posts
  has_many :line_posts
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :username
  validates_uniqueness_of :username
  
  def self.authenticate(username, password)
    user = find_by_username(username)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
	  @user = User.new

	end

	def create
	  @user = User.new(params[:user])
	  if @user.save
	    redirect_to root_url , :notice => "Signed up!, Now Log In!"
	  else
	    render "new"
	  end
	end

	def show
		@user = User.find(params[:id])
		@picks = @user.picks
		if current_user.id != @user.id
			redirect_to user_path(current_user), notice: "Acess Denied to Other Users"
		end
	end

	def index
		@users = User.all
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>All Users</h1>

  <% @users.each do |user| %>
    <h4><%= user.id %>    <%= user.username%></h4>

<% end %>

app/views/users/new.html.erb
<h1>Sign Up </h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/show.html.erb
<h2><center>Welcome to the Humboldt Fantasy Football Betting League</center></h2>
<div class = "row">
	<div class = "span6">
		<% if current_user.id != @user.id %>
			<h3>You Are Accessing A User's Page That Isn't Yours</h3>
		<% else %>

		<div style="border:1px solid black; padding-left:10%;">
			<h3><%= link_to "Send the President Your Weekly Picks" , new_user_pick_path(@user, @user.user_id) %> </h3>

			<h3><%= link_to "View My Weekly Picks" , user_picks_path(@user, @pick) %></h3>
		</div>

		<br>

		<div style="border:1px solid black; padding-left:10%;">
			<h3><%= link_to "League Picks", static_pick_history_path %></h3>

			<h3><%= link_to "Weekly Lines and Cash Bets", line_posts_path %></h3>
		</div>

		<br>

		<div style="border:1px solid black; padding-left:10%;">
			<h3><%= link_to "Message Board", posts_path %></h3>

			<h3><%= link_to "Show Standings", standing_path(1) %></h3>
		</div>

		<br>

		<div style="border:1px solid black; padding-left:10%;">

			<h3><%= link_to "BET2WIN", "http://bet2win.ag", :target => '_blank' %></h3>
			<h5>Username = ts104 Password = 123</h5>
			<h3><%= link_to "Pick Order" , static_pick_order_path %></h3>
			<h3><%= link_to "Rules" , static_rules_path %></h3>
		
		</div>

	</div>


	<div class = "span6">
		<div>
			<img src = "http://i.imgur.com/PbVsLKb.jpg">
		</div>
		<br>
		<% if current_user.id == 2 %>
		<h3><center>COMMISSIONER LINKS</center></h3>
			<div style="border:1px solid black; padding-left:3%">
			
			

	    	<h3><%= link_to "All Picks",  static_all_picks_path %></h3>

	    	<h3><%= link_to "Edit Standings", edit_standing_path(1) %></h3>

	    	<h3><%= link_to "Post Weekly Lines and Cash Bets", line_posts_path %></h3>
	    </div>
		<% end %> 
	</div>
</div>

<% end %>