config/routes.rb
HumboldtFantasy::Application.routes.draw do

  resources :line_posts
  resources :standings

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  
  get "static/example"

  get "static/all_picks"

  get "static/rules"

  get "static/pick_order"

  get "static/pick_history"

  root :to => "sessions#new"
  
  resources :users do
    resources :picks
  end

  resources :sessions

  resources :posts do
    resources :comments
  end
  
end

app/models/standing.rb
class Standing < ActiveRecord::Base
  attr_accessible :player1,
                  :player2,
                  :player3,
                  :player4,
                  :player5,
                  :player6,
                  :player7,
                  :player8,
                  :player9,
                  :player10,
                  :player11,
                  :player12,
                  :player13,
                  :player14,
                  :player15,
                  :player16,
                  :player17,
                  :player18,
                  :player19,
                  :player20,
                  :player21,
                  :player22,
                  :player23,
                  :player24,
                  :player25,
                  :player26,
                  :player27,
                  :player28,
                  :player29,
                  :player30,
                  :username1,
                  :username2,
                  :username3,
                  :username4,
                  :username5,
                  :username6,
                  :username7,
                  :username8,
                  :username9,
                  :username10,
                  :username11,
                  :username12,
                  :username13,
                  :username14,
                  :username15,
                  :username16,
                  :username17,
                  :username18,
                  :username19,
                  :username20,
                  :username21,
                  :username22,
                  :username23,
                  :username24,
                  :username25,
                  :username26,
                  :username27,
                  :username28,
                  :username29,
                  :username30
end

app/controllers/standings_controller.rb
class StandingsController < ApplicationController
  # GET /standings
  # GET /standings.json
  def index
    @standings = Standing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @standings }
    end
  end

  # GET /standings/1
  # GET /standings/1.json
  def show
    @standing = Standing.find(params[:id])

    @pointsArray = [[@standing.player1, @standing.username1],
                    [@standing.player2, @standing.username2],
                    [@standing.player3, @standing.username3],
                    [@standing.player4, @standing.username4],
                    [@standing.player5, @standing.username5],
                    [@standing.player6, @standing.username6],
                    [@standing.player7, @standing.username7],
                    [@standing.player8, @standing.username8],
                    [@standing.player9, @standing.username9],
                    [@standing.player10, @standing.username10],
                    [@standing.player11, @standing.username11],
                    [@standing.player12, @standing.username12],
                    [@standing.player13, @standing.username13],
                    [@standing.player14, @standing.username14],
                    [@standing.player15, @standing.username15],
                    [@standing.player16, @standing.username16],
                    [@standing.player17, @standing.username17],
                    [@standing.player18, @standing.username18],
                    [@standing.player19, @standing.username19],
                    [@standing.player20, @standing.username20],
                    [@standing.player21, @standing.username21],
                    [@standing.player22, @standing.username22],
                    [@standing.player23, @standing.username23],
                    [@standing.player24, @standing.username24],
                    [@standing.player25, @standing.username25],
                    [@standing.player26, @standing.username26],
                    [@standing.player27, @standing.username27],
                    [@standing.player28, @standing.username28],
                    [@standing.player29, @standing.username29],
                    [@standing.player30, @standing.username30]
                   ]

    @pointsArray = @pointsArray.sort_by{|a,b| a}.reverse
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @standing }
    end
  end

  # GET /standings/new
  # GET /standings/new.json
  def new
    @standing = Standing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @standing }
    end
  end

  # GET /standings/1/edit
  def edit
    @standing = Standing.find(params[:id])

    @pointsArray = [[@standing.player1, @standing.username1],
                    [@standing.player2, @standing.username2],
                    [@standing.player3, @standing.username3],
                    [@standing.player4, @standing.username4],
                    [@standing.player5, @standing.username5],
                    [@standing.player6, @standing.username6],
                    [@standing.player7, @standing.username7],
                    [@standing.player8, @standing.username8],
                    [@standing.player9, @standing.username9],
                    [@standing.player10, @standing.username10],
                    [@standing.player11, @standing.username11],
                    [@standing.player12, @standing.username12],
                    [@standing.player13, @standing.username13],
                    [@standing.player14, @standing.username14],
                    [@standing.player15, @standing.username15],
                    [@standing.player16, @standing.username16],
                    [@standing.player17, @standing.username17],
                    [@standing.player18, @standing.username18],
                    [@standing.player19, @standing.username19],
                    [@standing.player20, @standing.username20],
                    [@standing.player21, @standing.username21],
                    [@standing.player22, @standing.username22],
                    [@standing.player23, @standing.username23],
                    [@standing.player24, @standing.username24],
                    [@standing.player25, @standing.username25],
                    [@standing.player26, @standing.username26],
                    [@standing.player27, @standing.username27],
                    [@standing.player28, @standing.username28],
                    [@standing.player29, @standing.username29],
                    [@standing.player30, @standing.username30]
                   ]

    @pointsArray = @pointsArray.sort_by{|a,b| a}.reverse
  end

  # POST /standings
  # POST /standings.json
  def create
    @standing = Standing.new(params[:standing])

    respond_to do |format|
      if @standing.save
        format.html { redirect_to @standing, notice: 'Standing was successfully created.' }
        format.json { render json: @standing, status: :created, location: @standing }
      else
        format.html { render action: "new" }
        format.json { render json: @standing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /standings/1
  # PUT /standings/1.json
  def update
    @standing = Standing.find(params[:id])

    respond_to do |format|
      if @standing.update_attributes(params[:standing])
        format.html { redirect_to @standing, notice: 'Standing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @standing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /standings/1
  # DELETE /standings/1.json
  def destroy
    @standing = Standing.find(params[:id])
    @standing.destroy

    respond_to do |format|
      format.html { redirect_to standings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/standings_helper.rb
module StandingsHelper
end

app/views/standings/_form.html.erb
<%= form_for(@standing) do |f| %>
  <% if @standing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@standing.errors.count, "error") %> prohibited this standing from being saved:</h2>

      <ul>
      <% @standing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class = "row">
<div class = "span3">
  <div class="field">
    <%= f.label :player1 %>
    <%= f.text_field :username1 %>
    <%= f.number_field :player1 %>
    <br><br/>
    <%= f.label :player2 %>
    <%= f.text_field :username2 %>
    <%= f.number_field :player2 %>
    <br><br/>
    <%= f.label :player3 %>
    <%= f.text_field :username3 %>
    <%= f.number_field :player3 %>
    <br><br/>
    <%= f.label :player4 %>
    <%= f.text_field :username4 %>
    <%= f.number_field :player4 %>
    <br><br/>
    <%= f.label :player5 %>
    <%= f.text_field :username5 %>
    <%= f.number_field :player5 %>
    <br><br/>
    <%= f.label :player6 %>
    <%= f.text_field :username6 %>
    <%= f.number_field :player6 %>
    <br><br/>
    <%= f.label :player7 %>
    <%= f.text_field :username7 %>
    <%= f.number_field :player7 %>
    <br><br/>
     <%= f.label :player8 %>
     <%= f.text_field :username8 %>
     <%= f.number_field :player8 %>
    <br><br/>
     <%= f.label :player9 %>
     <%= f.text_field :username9 %>
     <%= f.number_field :player9 %>
    <br><br/>
     <%= f.label :player10 %>
     <%= f.text_field :username10 %>
     <%= f.number_field :player10 %>
    <br><br/>
  </div>
  </div>

<div class="span3">
  <div class= "field">
     <%= f.label :player11 %>
     <%= f.text_field :username11 %>
     <%= f.number_field :player11 %>
    <br><br/>
     <%= f.label :player12 %>
     <%= f.text_field :username12 %>
     <%= f.number_field :player12 %>
    <br><br/>
     <%= f.label :player13 %>
     <%= f.text_field :username13 %>
     <%= f.number_field :player13 %>
    <br><br/>
     <%= f.label :player14 %>
     <%= f.text_field :username14 %>
     <%= f.number_field :player14 %>
    <br><br/>
     <%= f.label :player15 %>
     <%= f.text_field :username15 %>
     <%= f.number_field :player15 %>
    <br><br/>
     <%= f.label :player16 %>
     <%= f.text_field :username16 %>
     <%= f.number_field :player16 %>
    <br><br/>
     <%= f.label :player17 %>
     <%= f.text_field :username17 %>
     <%= f.number_field :player17 %>
    <br><br/>
     <%= f.label :player18 %>
     <%= f.text_field :username18 %>
     <%= f.number_field :player18 %>
    <br><br/>
    <%= f.label :player19 %>
    <%= f.text_field :username19 %>
    <%= f.number_field :player19 %>
    <br><br/>
    <%= f.label :player20 %>
    <%= f.text_field :username20 %>
    <%= f.number_field :player20 %>
    <br><br/>
    </div>
    </div>
<div class="span3">
  <div class= "field">
    <%= f.label :player21 %>
    <%= f.text_field :username21 %>
    <%= f.number_field :player21 %>
    <br><br/>
    <%= f.label :player22 %>
    <%= f.text_field :username22 %>
    <%= f.number_field :player22 %>
    <br><br/>
    <%= f.label :player23 %>
    <%= f.text_field :username23 %>
    <%= f.number_field :player23 %>
    <br><br/>
    <%= f.label :player24 %>
    <%= f.text_field :username24 %>
    <%= f.number_field :player24 %>
    <br><br/>
    <%= f.label :player25 %>
    <%= f.text_field :username25 %>
    <%= f.number_field :player25 %>
    <br><br/>
    <%= f.label :player26 %>
    <%= f.text_field :username26 %>
    <%= f.number_field :player26 %>
    <br><br/>
    <%= f.label :player27 %>
    <%= f.text_field :username27 %>
    <%= f.number_field :player27 %>
    <br><br/>
    <%= f.label :player28 %>
    <%= f.text_field :username28 %>
    <%= f.number_field :player28 %>
    <br><br/>
    <%= f.label :player29 %>
    <%= f.text_field :username29 %>
    <%= f.number_field :player29 %>
    <br><br/>
    <%= f.label :player30 %>
    <%= f.text_field :username30 %>
    <%= f.number_field :player30 %>
    <br><br/>
  </div>    
  </div>
  <br><br/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/standings/edit.html.erb
<h1>Editing standing</h1>

<%= form_for(@standing) do |f| %>
  <% if @standing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@standing.errors.count, "error") %> prohibited this standing from being saved:</h2>

      <ul>
      <% @standing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class = "row">
<div class = "span3">
  <div class="field">
    <%= f.label @standing.username1 %>
    <%= f.number_field :player1 %>
    <br><br/>
    <%= f.label @standing.username2 %>
    <%= f.number_field :player2 %>
    <br><br/>
    <%= f.label @standing.username3 %>
    <%= f.number_field :player3 %>
    <br><br/>
    <%= f.label @standing.username4 %>
    <%= f.number_field :player4 %>
    <br><br/>
    <%= f.label @standing.username5 %>
    <%= f.number_field :player5 %>
    <br><br/>
    <%= f.label @standing.username6 %>
    <%= f.number_field :player6 %>
    <br><br/>
    <%= f.label @standing.username7 %>
    <%= f.number_field :player7 %>
    <br><br/>
     <%= f.label @standing.username8 %>
     <%= f.number_field :player8 %>
    <br><br/>
     <%= f.label @standing.username9 %>
     <%= f.number_field :player9 %>
    <br><br/>
     <%= f.label @standing.username10 %>
     <%= f.number_field :player10 %>
    <br><br/>
  </div>
  </div>

<div class="span3">
  <div class= "field">
  	 <%= f.label @standing.username11 %>
     <%= f.number_field :player11 %>
    <br><br/>
     <%= f.label @standing.username12 %>
     <%= f.number_field :player12 %>
    <br><br/>
     <%= f.label @standing.username13 %>
     <%= f.number_field :player13 %>
    <br><br/>
     <%= f.label @standing.username14 %>
     <%= f.number_field :player14 %>
    <br><br/>
     <%= f.label @standing.username15 %>
     <%= f.number_field :player15 %>
    <br><br/>
     <%= f.label @standing.username16 %>
     <%= f.number_field :player16 %>
    <br><br/>
     <%= f.label @standing.username17 %>
     <%= f.number_field :player17 %>
    <br><br/>
     <%= f.label @standing.username18 %>
     <%= f.number_field :player18 %>
    <br><br/>
    <%= f.label @standing.username19 %>
    <%= f.number_field :player19 %>
    <br><br/>
    <%= f.label @standing.username20 %>
    <%= f.number_field :player20 %>
    <br><br/>
    </div>
    </div>
<div class="span3">
  <div class= "field">
    <%= f.label @standing.username21 %>
    <%= f.number_field :player21 %>
    <br><br/>
    <%= f.label @standing.username22 %>
    <%= f.number_field :player22 %>
    <br><br/>
    <%= f.label @standing.username23 %>
    <%= f.number_field :player23 %>
    <br><br/>
    <%= f.label @standing.username24 %>
    <%= f.number_field :player24 %>
    <br><br/>
    <%= f.label @standing.username25 %>
    <%= f.number_field :player25 %>
    <br><br/>
    <%= f.label @standing.username26 %>
    <%= f.number_field :player26 %>
    <br><br/>
    <%= f.label @standing.username27 %>
    <%= f.number_field :player27 %>
    <br><br/>
    <%= f.label @standing.username28 %>
    <%= f.number_field :player28 %>
    <br><br/>
    <%= f.label @standing.username29 %>
    <%= f.number_field :player29 %>
    <br><br/>
    <%= f.label @standing.username30 %>
    <%= f.number_field :player30 %>
    <br><br/>
  </div>    
  </div>
  <br><br/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/standings/index.html.erb
<h1>Standings, Click Show</h1>

<table>
<% @standings.each do |standing| %>
  <tr>
    <td><%= link_to 'Show', standing %></td>
  </tr>
<% end %>
</table>

app/views/standings/new.html.erb
<h1>New standing</h1>

<%= render 'form' %>

<%= link_to 'Back', standings_path %>

app/views/standings/show.html.erb
<p id="notice"><%= notice %></p>

<h2>HUMBOLDT FANTASY BETTING LEAGUE STANDINGS</h2>
<br>
<br>
<div class="row">
  <div class="span4">
    <table class = "gridtable">  
      <tbody>
        <tr>
          <th>1</th><td><%=@pointsArray[0][1]%></td><td><%=@pointsArray[0][0]%></td></tr><tr>
          <th>2</th><td><%=@pointsArray[1][1]%></td><td><%=@pointsArray[1][0]%></td></tr><tr>
          <th>3</th><td><%=@pointsArray[2][1]%></td><td><%=@pointsArray[2][0]%></td></tr><tr>
          <th>4</th><td><%=@pointsArray[3][1]%></td><td><%=@pointsArray[3][0]%></td></tr><tr>
          <th>5</th><td><%=@pointsArray[4][1]%></td><td><%=@pointsArray[4][0]%></td></tr><tr>
          <th>6</th><td><%=@pointsArray[5][1]%></td><td><%=@pointsArray[5][0]%></td></tr><tr>
          <th>7</th><td><%=@pointsArray[6][1]%></td><td><%=@pointsArray[6][0]%></td></tr><tr>
          <th>8</th><td><%=@pointsArray[7][1]%></td><td><%=@pointsArray[7][0]%></td></tr><tr>
          <th>9</th><td><%=@pointsArray[8][1]%></td><td><%=@pointsArray[8][0]%></td></tr><tr>
          <th>10</th><td><%=@pointsArray[9][1]%></td><td><%=@pointsArray[9][0]%></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="span4">
    <table class = "gridtable">  
      <tbody>
        <tr>
          <th>11</th><td><%=@pointsArray[10][1]%></td><td><%=@pointsArray[10][0]%></td></tr><tr>
          <th>12</th><td><%=@pointsArray[11][1]%></td><td><%=@pointsArray[11][0]%></td></tr><tr>
          <th>13</th><td><%=@pointsArray[12][1]%></td><td><%=@pointsArray[12][0]%></td></tr><tr>
          <th>14</th><td><%=@pointsArray[13][1]%></td><td><%=@pointsArray[13][0]%></td></tr><tr>
          <th>15</th><td><%=@pointsArray[14][1]%></td><td><%=@pointsArray[14][0]%></td></tr><tr>
          <th>16</th><td><%=@pointsArray[15][1]%></td><td><%=@pointsArray[15][0]%></td></tr><tr>
          <th>17</th><td><%=@pointsArray[16][1]%></td><td><%=@pointsArray[16][0]%></td></tr><tr>
          <th>18</th><td><%=@pointsArray[17][1]%></td><td><%=@pointsArray[17][0]%></td></tr><tr>
          <th>19</th><td><%=@pointsArray[18][1]%></td><td><%=@pointsArray[18][0]%></td></tr><tr>
          <th>20</th><td><%=@pointsArray[19][1]%></td><td><%=@pointsArray[19][0]%></td></tr>
      </tbody>
    </table>
  </div>

  <div class="span4">
    <table class = "gridtable">  
      <tbody>
        <tr>
          <th>21</th><td><%=@pointsArray[20][1]%></td><td><%=@pointsArray[20][0]%></td></tr><tr>
          <th>22</th><td><%=@pointsArray[21][1]%></td><td><%=@pointsArray[21][0]%></td></tr><tr>
          <th>23</th><td><%=@pointsArray[22][1]%></td><td><%=@pointsArray[22][0]%></td></tr><tr>
          <th>24</th><td><%=@pointsArray[23][1]%></td><td><%=@pointsArray[23][0]%></td></tr><tr>
          <th>25</th><td><%=@pointsArray[24][1]%></td><td><%=@pointsArray[24][0]%></td></tr><tr>
          <th>26</th><td><%=@pointsArray[25][1]%></td><td><%=@pointsArray[25][0]%></td></tr><tr>
          <th>27</th><td><%=@pointsArray[26][1]%></td><td><%=@pointsArray[26][0]%></td></tr><tr>
          <th>28</th><td><%=@pointsArray[27][1]%></td><td><%=@pointsArray[27][0]%></td></tr><tr>
          <th>29</th><td><%=@pointsArray[28][1]%></td><td><%=@pointsArray[28][0]%></td></tr><tr>
          <th>30</th><td><%=@pointsArray[29][1]%></td><td><%=@pointsArray[29][0]%></td></tr>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
<% if current_user.id == 2 %>
    <h3><%= link_to 'Edit', edit_standing_path(@standing) %></h3>
   <% end %>
</div>