config/routes.rb
HumboldtFantasy::Application.routes.draw do

  resources :line_posts
  resources :standings

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  
  get "static/example"

  get "static/all_picks"

  get "static/rules"

  get "static/pick_order"

  get "static/pick_history"

  root :to => "sessions#new"
  
  resources :users do
    resources :picks
  end

  resources :sessions

  resources :posts do
    resources :comments
  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Humboldt Fantasy</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Humboldt Fantasy Betting League</a>
        <div class="nav-collapse">
          <ul class="nav">
            <% if current_user %>
              <li><%= link_to "Home" , user_path(current_user) %></li>

              <li><%= link_to "Log out", log_out_path %></li>

              </div>
              <ul class="nav pull-right">
              <a class="brand" href="#"><%= current_user.username %></a>

          </ul>
               <% else %>

                  <li><%= link_to "Log in", log_in_path %></li>

              <% end %>
          </ul>
          
        </div>
      </div>
    </div>
  </div>

<div class = "mainContent">
 <div class="container">
    <div class="row">
    <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>">
              <%= value %>
        </div>
  <% end %>
      <div class="span12" style = "float: none; margin: 0 auto;"><%= yield %></div>
    </div>
  </div>
</div>

</body>
</html>